/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2018-01-19 12:40:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ticket_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Ticket</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("    <!-- jQuery library -->\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("    <!-- Latest compiled JavaScript -->\r\n");
      out.write("    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <header>\r\n");
      out.write("        <nav class=\"navbar navbar-default\">\r\n");
      out.write("            <div class=\"container-fluid\">\r\n");
      out.write("                <div class=\"navbar-header\">\r\n");
      out.write("                    <a class=\"navbar-brand\" href=\"#\">Agile Management</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <ul class=\"nav navbar-nav\">\r\n");
      out.write("                    <li><a href=\"#\">Tickets</a></li>\r\n");
      out.write("                    <li><a href=\"ticket.html\">Sprints</a></li>\r\n");
      out.write("                    <li><a href=\"#\">Projects</a></li>\r\n");
      out.write("                    <li><a href=\"#\" class=\"user\"><i class=\"fa fa-user\"></i> ");
      out.print(session.getAttribute("userKey"));
      out.write("</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("    <ul class=\"dashboard clearfix\">\r\n");
      out.write("        <li class=\"divider-2\">\r\n");
      out.write("            <a href=\"#\" class=\"dash-title\">Project Name</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"divider-2\">\r\n");
      out.write("            <a href=\"newticket.html\"><button class=\"btn-sm btn-style first-btn\"><i class=\"fa fa-envelope-square icon-style\" aria-hidden=\"true\"></i>New Ticket</button></a>\r\n");
      out.write("            <button class=\"btn-sm btn-style\"><i class=\"fa fa-clock-o icon-style\" aria-hidden=\"true\"></i>Add Time</button>\r\n");
      out.write("            <button class=\"btn-sm btn-style\"><i class=\"fa fa-upload icon-style\" aria-hidden=\"true\"></i>Upload File</button>\r\n");
      out.write("        </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-1\"></div>\r\n");
      out.write("            <div class=\"col-md-7\">\r\n");
      out.write("                <h3>Your Project has been created!</h3>\r\n");
      out.write("                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis cupiditate quos mollitia delectus sed minus doloribus, enim temporibus. Tempore, soluta. Aliquam eius nam odio! Voluptas neque itaque facilis labore velit.</p>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li class=\"list-style\">\r\n");
      out.write("                    \t<i class=\"fa fa-git icon-style\"></i>\r\n");
      out.write("                    \t<a href=\"#\">Create new git, Subversion  or mercurial repository to push your code</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"list-style\">\r\n");
      out.write("                    \t<i class=\"fa fa-plus-circle icon-style\"></i>\r\n");
      out.write("                    \t<a href=\"#\">Add your user Stories by building your project backlog </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"list-style\">\r\n");
      out.write("                    \t<i class=\"fa fa-repeat icon-style\"></i>\r\n");
      out.write("                    \t<a href=\"#\">Use your project Backlog to plan your first sprint</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-3\"></div>\r\n");
      out.write("            <div class=\"col-md-1\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <footer>\r\n");
      out.write("        <ul class=\"foot-content\">\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"#\">Blog</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"#\">Twitter</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"#\">Terms & Conditions</a>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
